title: 4b memo
email: your-email@example.com
description: "4b のやったことについて"
github_username: Shibungi

# Build settings
markdown: kramdown
# theme: jekyll-theme-architect
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed